#!/bin/sh -e
# Creates repo structure in current directory with symlinks to APT-style repo used in ALT Linux;

[ -z "$1" ] && echo "${0##*/}:you should give path to ALT Linux repo" >&2 && exit 1
ALT="$1"

for i in noarch i586 x86_64; do
    /bin/mkdir "$i"
    /bin/ln -s "$ALT/files/$i/RPMS" "$i/RPMS"
    /bin/ln -s "$ALT/files/SRPMS" "$i/SRPMS"
done
