#!/bin/sh -e
# Builds full valid repo indices;

COMPRESSION=none
VENDOR='ALt Linux'
NAME=Sisyphus

genbasedir -c "$COMPRESSION" -r -d i586/RPMS:x86_64/RPMS -p "$PATH" -u "name=$NAME" -u "vendor=$VENDOR" -l noarch
genbasedir -c "$COMPRESSION" -r -d noarch/RPMS -p "$PATH" -u "name=$NAME" -u "vendor=$VENDOR" -l i586
genbasedir -c "$COMPRESSION" -r -d noarch/RPMS -p "$PATH" -u "name=$NAME" -u "vendor=$VENDOR" -l x86_64
